#!/usr/bin/env sh

## Do copy annotation classes from annotation module to adapter module
TARGET_PATH="./router/src/main/java/com/github/boybeak/router/annotation"
SOURCE_PATH="./router-annotation/src/main/java/com/github/boybeak/router/annotation"
rm -rf "$TARGET_PATH"
cp -rf "$SOURCE_PATH" "$TARGET_PATH"

## Do ./gradlew adapter:install
./gradlew router:install

## Do ./gradlew adapter:bintrayUpload
./gradlew router:bintrayUpload
